server:
  port: 8052
spring:
   data:
     mongodb:
           database: RFQ
           host: localhost
           port: 27017
eureka:
     client:
       serviceUrl:
        defaultZone: http://localhost:8787/eureka/        
          
graphql:
    graphiql:
        enabled: true   
               
          