server:
  port: 8052
spring:
   data:
     mongodb:
           database: RFQ
           host: localhost
           port: 27017
   jpa:
     generate-ddl: true
     show-sql: true
   graphql:
      graphiql:
         enabled: true
   
eureka:
     client:
       serviceUrl:
        defaultZone: http://localhost:8761/eureka/        
          